apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: kadhir22/demo
        
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort  # Makes it accessible outside the cluster
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30077  # Exposes on port 30077
